admin/models.py
from database import Base, session
from sqlalchemy import Column, ForeignKey, Table
from sqlalchemy.orm import relationship, backref
from sqlalchemy.types import String, Integer, Float


# User - пользователи из телеграм


class User(Base):
	__abstract__ = True


class Admin(User):

	__tablename__ = 'admins'

	id = Column(Integer(), primary_key=True)
	name = Column(String())

	def __init__(self, name: str):
		self.name = name 


class Tg_User(User):

	__tablename__ = 'tg_users'

	id = Column(Integer(), primary_key=True)
	username = Column(String())
	first_name = Column(String())

	def __init__(self, id: int, username: str, first_name: str):
		self.id = id
		self.username = username
		self.first_name = first_name


class Product(Base):

	__tablename__ = 'products'

	id = Column(Integer(), primary_key=True)
	category = Column(Integer(), ForeignKey('category.id'))
	name = Column(String())
	description = Column(String())
	price = Column(Float())
	image = Column(String())


	def __init__(
		self, 
		name: str, 
		category: int, 
		description: str, 
		price: float, 
		image: str
		):
		self.name = name
		self.category = category
		self.description = description
		self.price = price
		self.image = image


class Category(Base):

	__tablename__ = 'category'

	id = Column(Integer(), primary_key=True)
	name = Column(String(), unique=True)
	products_list = relationship("Product")

	def __init__(self, name):
		self.name = name

	def get_products(self) -> list:
		return self.products_list


	@staticmethod
	def get_all_category():
		return session.query(Category).all()


# cart_products = Table(
# 	"cart_products",
# 	Base.metadata,
# 	Column("cart_id", ForeignKey("carts.id")),
# 	Column("product_id", ForeignKey("products.id"))
# )


# class Cart(Base):

# 	__tablename__ = 'carts'

# 	id = Column(Integer(), primary_key=True)
# 	user_id = Column(Integer(), ForeignKey('tg_users.id'))
# 	owner = relationship("Tg_User", back_populates="cart")
# 	products_list = relationship("Product", secondary=cart_products, backref=backref("in_carts", lazy="dynamic"))
# 	summ = Column(Float)

# 	def __init__(self, user_id: int, owner: Tg_User) -> None:
# 		self.user_id = user_id
# 		self.owner = owner
# 		self.summ = 0

# 	def add_product(self, product: Product) -> None:
# 		self.summ = self.summ + product.price
# 		self.products_list.append(product)


# 	def remove_product(self, product: Product) -> None:	 
# 		if product in self.products_list:
# 			self.summ = self.summ - product.price
# 			self.products_list.remove(product)

	
# 	def get_products(self) -> list:
# 		return self.products_list

	
# 	def get_cart_summ(self) -> float:
# 		return self.summ


	

	

admin/views.py
from crypt import methods
from http.client import HTTPResponse
import os
# from http.client import HttpResponse
from flask import Blueprint, render_template, request, redirect, url_for, jsonify, make_response, Response
from database import Base, session
from admin.models import Admin, Tg_User, Product, Category
from mytools import allowed_file
from werkzeug.utils import secure_filename
from database import BASEDIR
from myform import ProductForm, ProductFormEdit
from log import logger


admin = Blueprint('admin', __name__, template_folder='templates', static_folder='static')


@admin.route('/admin')
def index():


	return render_template('admin/dashboard/index.html')


@admin.route('/pay')
def pay():
	return render_template('admin/dashboard/pay.html')


@admin.route('/products')
def products():
	print("krtrkjtnkrjn")
	products_list = session.query(Product).all()
	category_list = session.query(Category).all()

	return render_template('admin/product/index.html', products_list=products_list, category_list=category_list)


@admin.route('/add_category', methods=['GET', 'POST'])
def add_category():
	if request.method == 'POST':
		name = request.form.get('name')
		session.add(Category(name))
		session.commit()
		return redirect(url_for('admin.products'))
	return render_template('admin/product/add_category.html')


@admin.route('/delete_product/<product_id>', methods=['GET'])
def delete_product(product_id):
	session.query(Product).filter(Product.id == int(product_id)).delete()
	return redirect(url_for('admin.products'))



@admin.route('/edit_product/<pr_id>', methods=['GET', 'POST'])
def edit_product(pr_id):
	
	product = session.query(Product).filter(Product.id == int(pr_id)).first()

	form = ProductFormEdit()

	form.category.choices = [(cat.id, cat.name) for cat in session.query(Category).all()]
	form.category.default = product.category

	if request.method == 'POST':
		name = form.name.data
		price = form.price.data
		description = form.description.data
		image = form.image.data
		imagename = ''
		if image and allowed_file(image.filename):
			imagename = secure_filename(image.filename)
			image.save(os.path.join(BASEDIR, imagename))
		category = form.category.data

		new_data = {
			Product.name: name, Product.category: int(category),
			Product.description: description, Product.price: price, 
			Product.image: imagename
		}
		for key, value in list(new_data.items()):
			if value == '':
				del new_data[key]
		print(new_data)


		session.query(Product).filter(Product.id == int(pr_id)).update(new_data)
		session.commit()

		return redirect(url_for('admin.products'))
	return render_template('admin/product/edit_product.html', form=form, product=product)


@admin.route('/pay_ok', methods=['POST'])
def pay_ok():
	#text = request.get_json()
	print(request.form)
	print("ok")
	return "success", 200


@admin.route('/pay_fail/<invoiceId>', methods=['POST'])
def pay_fail(invoiceId):
	print("bad", invoiceId)
	return "success", 200


@admin.route('/get_categories', methods=['GET'])
def get_categories():

	categories = session.query(Category).all()

	#respns = jsonify({'code': 200, 'data': categories}).headers.add('Access-Control-Allow-Origin', '*')

	# Преобразование в список словаре
	categories_list = [category.__dict__ for category in categories]
	# Удаление служебного атрибута _sa_instance_state
	logger.info(categories_list)
	category_dict = {}
	for category_dict in categories_list:
		category_dict.pop('_sa_instance_state', None)

	logger.info(categories_list)
	resp = make_response(categories_list)
	resp.headers.add('Access-Control-Allow-Origin', '*')

	return resp

@admin.route('/get_products', methods=['GET'])
def get_products():

	products = session.query(Product).all()

	# Преобразование в список словаре
	products_list = [product.__dict__ for product in products]
	# Удаление служебного атрибута _sa_instance_state
	for products_dict in products_list:
		products_dict.pop('_sa_instance_state', None)

	resp = make_response(products_list)
	resp.headers.add('Access-Control-Allow-Origin', '*')

	return resp

@admin.route('/add_product', methods=['GET', 'POST'])
def add_product():
	
	form = ProductForm()

	form.category.choices = [(cat.id, cat.name) for cat in session.query(Category).all()]

	if request.method == 'POST':

		name = form.name.data
		price = form.price.data
		description = form.description.data
		image = form.image.data
		if image and allowed_file(image.filename):
			imagename = secure_filename(image.filename)
			image.save(os.path.join(BASEDIR, imagename))
		else:
			imagename = 'default.png'
		category = form.category.data

		session.add(Product(name, int(category), description, price, imagename))
		session.commit()

		return redirect(url_for('admin.products'))
	
	return render_template('admin/product/add_product.html', form=form)

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Dashboard Template · Bootstrap v5.1</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/dashboard/">

    

    <!-- Bootstrap core CSS -->
<link href="../static/assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="../static/assets/dist/css/dashboard.css" rel="stylesheet">
  </head>
  <body>
    
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Company name</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
  <div class="navbar-nav">
    <div class="nav-item text-nowrap">
      <a class="nav-link px-3" href="#">Sign out</a>
    </div>
  </div>
</header>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{url_for('admin.index')}}">
              <span data-feather="home"></span>
              Dashboard
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file"></span>
              Orders
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('admin.products')}}">
              <span data-feather="shopping-cart"></span>
              Products
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="users"></span>
              Customers
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="bar-chart-2"></span>
              Reports
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="layers"></span>
              Integrations
            </a>
          </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Saved reports</span>
          <a class="link-secondary" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Current month
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Last quarter
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Social engagement
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Year-end sale
            </a>
          </li>
        </ul>
      </div>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      
      {% block content %}{% endblock %}
<!--
      <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas>

-->   
    </main>
  </div>
</div>


    <script src="../static/assets/dist/js/bootstrap.bundle.min.js"></script>

      <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script><script src="../static/assets/dist/js/dashboard.js"></script>
  </body>
</html>

templates/sign-in/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Signin Template · Bootstrap v5.1</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/sign-in/">

    

    <!-- Bootstrap core CSS -->
<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="signin.css" rel="stylesheet">
  </head>
  <body class="text-center">
    
<main class="form-signin">
  <form>
    <img class="mb-4" src="../assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">
    <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

    <div class="form-floating">
      <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
      <label for="floatingInput">Email address</label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
      <label for="floatingPassword">Password</label>
    </div>

    <div class="checkbox mb-3">
      <label>
        <input type="checkbox" value="remember-me"> Remember me
      </label>
    </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
    <p class="mt-5 mb-3 text-muted">&copy; 2017–2021</p>
  </form>
</main>


    
  </body>
</html>